---
all:
  vars:
    ansible_user: ubuntu
    ansible_become: true
  children:
    control:
      hosts:
        localhost:
          ansible_connection: local
    k8s_master:
      hosts:
        master-1:
          ansible_host: 192.168.56.10
    k8s_worker:
      hosts:
        worker-1:
          ansible_host: 192.168.56.11
        worker-2:
          ansible_host: 192.168.56.12

