---
all:
  children:
    masters:
      hosts:
        kind-master:
          ansible_host: 192.168.136.128
          ansible_user: root
          ansible_connection: local
    workers:
      hosts:
        kind-node:
          ansible_host: 192.168.136.129
          ansible_user: root

