---
k8s_apt_keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
k8s_repo_line: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
calico_manifest_url: "https://raw.githubusercontent.com/projectcalico/calico/v3.27.4/manifests/calico.yaml"
kubeconfig_path: /etc/kubernetes/admin.conf

